- SafeguardDotNet/ISafeguardA2AContext.cs
- SafeguardDotNet/ISafeguardConnection.cs
- SafeguardDotNet/ISafeguardEventListener.cs
- SafeguardDotNet/SafeguardA2AContext.cs
- SafeguardDotNet/SafeguardConnection.cs
- SafeguardDotNet/SafeguardEventListener.cs
- Test/SafeguardDotNetEventTool/Program.cs
- Test/SafeguardDotNetEventTool/ToolOptions.cs
Removed a few endpoints that weren't useful
Added some debug and logging
Fixed up a few exceptions
> A few small refactors

- SafeguardDotNet/SafeguardDotNet.csproj
- appveyor.yml
Forgot a couple things when I released the initial version.
> Add OneIdentity to assembly name, release notes

- SafeguardDotNet.sln
- SafeguardDotNet/A2A/BrokeredAccessRequest.cs
- SafeguardDotNet/A2A/ISafeguardA2AContext.cs
- SafeguardDotNet/A2A/SafeguardA2AContext.cs
- SafeguardDotNet/SafeguardConnection.cs
- Test/SafeguardDotNetAccessRequestBrokerTool/Program.cs
- Test/SafeguardDotNetAccessRequestBrokerTool/SafeguardDotNetAccessRequestBrokerTool.csproj
- Test/SafeguardDotNetAccessRequestBrokerTool/ToolOptions.cs
Added support for calling the access request broker
Added a test tool for calling access request broker
> A2A support for access request broker

- SafeguardDotNet/A2A/SafeguardA2AContext.cs
- SafeguardDotNet/Authentication/AccessTokenAuthenticator.cs
- SafeguardDotNet/Authentication/CertificateAuthenticator.cs
- SafeguardDotNet/Authentication/PasswordAuthenticator.cs
- SafeguardDotNet/Event/PersistentSafeguardA2AEventListener.cs
- SafeguardDotNet/Event/SafeguardEventListener.cs
- SafeguardDotNet/SafeguardDotNet.csproj
- Samples/SampleA2aService/Program.cs
- Samples/SampleA2aService/SampleA2aService.csproj
- Samples/SampleA2aService/SampleService.cs
Cleaned up the sample project
Fixed some parameter checking
Updated the release notes
> Fixed a bug with A2A context creation using a thumbprint

- SafeguardDotNet.GuiLogin/LoginWindow.cs
- SafeguardDotNet.sln
- SafeguardDotNet/A2A/SafeguardA2AContext.cs
- SafeguardDotNet/Authentication/AnonymousAuthenticator.cs
- SafeguardDotNet/Authentication/AuthenticatorBase.cs
- SafeguardDotNet/Authentication/CertificateAuthenticator.cs
- SafeguardDotNet/Authentication/PasswordAuthenticator.cs
- SafeguardDotNet/SafeguardConnection.cs
- SafeguardDotNet/SafeguardDotNetException.cs
- Test/Invoke-SafeguardDotNetTests.ps1
- Test/SafeguardDotNetExceptionTest/Program.cs
- Test/SafeguardDotNetExceptionTest/SafeguardDotNetExceptionTest.csproj
- Test/SafeguardDotNetExceptionTest/TestOptions.cs
- Test/SafeguardDotNetTool/Program.cs
Added HttpStatusCode, Safeguard ErrorCode, and Safeguard ErrorMessage to SafeguardDotNetExceptions.  This makes error handling easier.
Added an integration test for SafeguardDotNetExceptions.
Found some issues with SafeguardDotNet where exceptions were not being thrown properly or where being nested unnecessarily.
> Improved SafeguardDotNetExceptions

- appveyor.yml
Encrypted API key for Appveyor to push to Nuget.org
> updated api key for pushing to nuget

- SafeguardDotNet/CertificateUtilities.cs
> Updated thumbprint comparison for certificate authentication to be case insensitive.

- SafeguardDotNet/A2A/SafeguardA2AContext.cs
- SafeguardDotNet/SafeguardDotNetTypes.cs
- Test/Invoke-SafeguardDotNetTests.ps1
- Test/SafeguardDotNetA2aTool/Program.cs
- Test/SafeguardDotNetA2aTool/SafeguardDotNetA2aTool.csproj
- Test/SafeguardDotNetA2aTool/ToolOptions.cs
Resolution for #87
Object now contains AssetNetworkAddress
> Allow retrieve network address via a2a discovery

- build-publish.yml
Service connections don't work for nuget.org
> publish with apikey from vault

- SafeguardDotNet.GuiLogin/LoginWindow.cs
- SafeguardDotNet.GuiLogin/RstsWindow.cs
- SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
- SafeguardDotNet.GuiLogin/packages.config
- SafeguardDotNet/A2A/BrokeredAccessRequest.cs
- SafeguardDotNet/Authentication/AuthenticatorBase.cs
- SafeguardDotNet/Authentication/CertificateAuthenticator.cs
- SafeguardDotNet/Authentication/PasswordAuthenticator.cs
- SafeguardDotNet/Event/EventHandlerRegistry.cs
- SafeguardDotNet/SafeguardConnection.cs
- SafeguardDotNet/SafeguardDotNet.csproj
- Test/SafeguardDotNetA2aTool/Program.cs
- Test/SafeguardDotNetA2aTool/SafeguardDotNetA2aTool.csproj
- Test/SafeguardDotNetAccessRequestBrokerTool/Program.cs
- Test/SafeguardDotNetAccessRequestBrokerTool/SafeguardDotNetAccessRequestBrokerTool.csproj
- Test/SafeguardDotNetEventTool/Program.cs
- Test/SafeguardDotNetEventTool/SafeguardDotNetEventTool.csproj
- Test/SafeguardDotNetExceptionTest/Program.cs
- Test/SafeguardDotNetExceptionTest/SafeguardDotNetExceptionTest.csproj
- Test/SafeguardDotNetGuiTester/Program.cs
- Test/SafeguardDotNetGuiTester/SafeguardDotNetGuiTester.csproj
- Test/SafeguardDotNetGuiTester/packages.config
- Test/SafeguardDotNetTool/Program.cs
- Test/SafeguardDotNetTool/SafeguardDotNetTool.csproj
Staying up with security and quality improvements in dependencies
> third-party component upgrades

- SafeguardDotNet/PersistentSafeguardConnection.cs
- SafeguardDotNet/Safeguard.cs
Class wraps the existing SafeguardConnection class and also implements ISafeguardConnection iface.
> Added Persistent Safeguard Connection class which renews expired auth tokens

- SafeguardDotNet/IStreamingRequest.cs
- SafeguardDotNet/StreamResponse.cs
- SafeguardDotNet/StreamingRequest.cs
- Test/SafeguardDotNetTool/Program.cs
Return the download stream as a StreamResponse which can be disposed to clean up all the stream-related resources (Request, Stream, progress handler) at once.
Consolidate some duplicated code and break up the functions a bit
> Add DownloadStreamAsync

- SafeguardDotNet/ISafeguardConnection.cs
- SafeguardDotNet/ISafeguardSessionsConnection.cs
- SafeguardDotNet/JoinRequest.cs
- SafeguardDotNet/PersistentSafeguardConnection.cs
- SafeguardDotNet/SafeguardConnection.cs
- SafeguardDotNet/SafeguardForPrivilegedSessions.cs
- SafeguardDotNet/SafeguardSessionsConnection.cs
- Test/README.md
- Test/SafeguardSessionsDotNetTool/Program.cs
- Test/SafeguardSessionsDotNetTool/SafeguardSessionsDotNetTool.csproj
- Test/SafeguardSessionsDotNetTool/ToolOptions.cs
Add support for basic Safeguard for Privileged Sessions configuration and also to join SPP and SPS.
> Safeguard and Safeguard for Privileged Sessions join

- SafeguardDotNet/SafeguardConnection.cs
use post method for join request instead of get
> fix SafeguardConnection joinSPS function

- SafeguardDotNet.sln
- SafeguardDotNet/ISafeguardConnection.cs
- SafeguardDotNet/ISafeguardSessionsConnection.cs
- SafeguardDotNet/JoinRequest.cs
- SafeguardDotNet/PersistentSafeguardConnection.cs
- SafeguardDotNet/SafeguardConnection.cs
- SafeguardDotNet/SafeguardForPrivilegedSessions.cs
- SafeguardDotNet/SafeguardSessionsConnection.cs
- SafeguardDotNet/StreamResponse.cs
- SafeguardDotNet/StreamingRequest.cs
- Test/SafeguardSessionsDotNetTool/Program.cs
- build-publish.yml
Added the SafeguardSessionsTool to the main sln file
Added a convenience method to ISafeguardSessionConnection that just returns a string, InvokeMethod().
Cleaned up some code and formatting issues.
I changed the signature of JoinSPS to JoinSps to be consistent for naming.  Any code using the prerelease will need to make a code change to get that update.
> A few updates before release

- SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
- SafeguardDotNet.GuiLogin/packages.config
- SafeguardDotNet/SafeguardDotNet.csproj
- Test/SafeguardDotNetA2aTool/SafeguardDotNetA2aTool.csproj
- Test/SafeguardDotNetAccessRequestBrokerTool/SafeguardDotNetAccessRequestBrokerTool.csproj
- Test/SafeguardDotNetBrowserLoginTester/SafeguardDotNetBrowserLoginTester.csproj
- Test/SafeguardDotNetEventTool/SafeguardDotNetEventTool.csproj
- Test/SafeguardDotNetExceptionTest/SafeguardDotNetExceptionTest.csproj
- Test/SafeguardDotNetGuiTester/SafeguardDotNetGuiTester.csproj
- Test/SafeguardDotNetGuiTester/packages.config
- Test/SafeguardDotNetTool/SafeguardDotNetTool.csproj
- Test/SafeguardSessionsDotNetTool/SafeguardSessionsDotNetTool.csproj
Not upgrading to SignalR 6
Not upgrading to latest RestSharp because of outstanding issues with 108 package
> Nuget package updates

- SafeguardDotNet.BrowserLogin/SafeguardDotNet.BrowserLogin.csproj
- SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
- SafeguardDotNet.GuiLogin/app.config
- SafeguardDotNet.GuiLogin/packages.config
- SafeguardDotNet/SafeguardDotNet.csproj
- Test/Invoke-SafeguardDotNetTests.ps1
- Test/README.md
- Test/SafeguardDotNetA2aTool/SafeguardDotNetA2aTool.csproj
- Test/SafeguardDotNetAccessRequestBrokerTool/SafeguardDotNetAccessRequestBrokerTool.csproj
- Test/SafeguardDotNetBrowserLoginTester/SafeguardDotNetBrowserLoginTester.csproj
- Test/SafeguardDotNetEventTool/SafeguardDotNetEventTool.csproj
- Test/SafeguardDotNetExceptionTest/Program.cs
- Test/SafeguardDotNetExceptionTest/SafeguardDotNetExceptionTest.csproj
- Test/SafeguardDotNetGuiTester/App.config
- Test/SafeguardDotNetGuiTester/SafeguardDotNetGuiTester.csproj
- Test/SafeguardDotNetGuiTester/packages.config
- Test/SafeguardDotNetTool/SafeguardDotNetTool.csproj
- Test/SafeguardSessionsDotNetTool/SafeguardSessionsDotNetTool.csproj
Also,
Fix issues caused by packages upgrades
Target .Net 6.0 for test programs
> Update nuget packages

- versionnumber.ps1
Version number must be between 0 and 65534
Mod is a better way to accomplish this
> Fix the build

- SafeguardDotNet/A2A/ISafeguardA2AContext.cs
- SafeguardDotNet/A2A/SafeguardA2AContext.cs
- SafeguardDotNet/A2A/SshKey.cs
- Test/Invoke-SafeguardDotNetTests.ps1
- Test/SafeguardDotNetA2aTool/Program.cs
- Test/SafeguardDotNetA2aTool/ToolOptions.cs
Add the test to the automated scripts and unit test program.
> Expose the SPP endpoints in Safeguarddotnet to set a password or ssh private key.

- SafeguardDotNet/A2A/SafeguardEventListenerState.cs
- SafeguardDotNet/Event/ISafeguardEventListener.cs
- SafeguardDotNet/Event/PersistentSafeguardEventListenerBase.cs
- SafeguardDotNet/Event/SafeguardEventListener.cs
- Test/SafeguardDotNetEventTool/Program.cs
- Test/SafeguardDotNetEventTool/ToolOptions.cs
If a callback is set, it will get called each time the signalr connection state changes.
> Add an event listener callback to get the current state of the Signalr connection.

- SafeguardDotNet/ISafeguardConnection.cs
- SafeguardDotNet/PersistentSafeguardConnection.cs
- SafeguardDotNet/SafeguardConnection.cs
Needed for a zero-interaction replica add in SGDOSE.
> Allow caller to retrieve the AccessToken for the connection. 

- SafeguardDotNet.GuiLogin/Properties/AssemblyInfo.cs
- SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
- SafeguardDotNet.GuiLogin/app.config
- SafeguardDotNet.GuiLogin/packages.config
- Samples/ServiceNowTicketValidator/Properties/AssemblyInfo.cs
- Test/SafeguardDotNetGuiTester/App.config
- Test/SafeguardDotNetGuiTester/Properties/AssemblyInfo.cs
- Test/SafeguardDotNetGuiTester/SafeguardDotNetGuiTester.csproj
- build-publish.yml
- pipeline-templates/global-variables.yml
Change the build number for Safeguard 8.0. Change the Azure Subscription name/service connection. Update/use the latest `AzureKeyVault` build task.
> Update Build Pipeline Scripts/Service Connection

- pipeline-templates/global-variables.yml
Publish an official release to NuGet.
> Safeguard 8.0 Release

- Samples/SampleA2aService/README.md
- Samples/SampleA2aService/SampleA2aService.csproj
- Samples/SampleA2aService/app.config
- Samples/ServiceNowTicketValidator/ServiceNowTicketValidator.csproj
- Samples/ServiceNowTicketValidator/app.config
- pipeline-templates/global-variables.yml
New Release branch with version change
> New Release branch 

- pipeline-templates/global-variables.yml
Updating the isPrerelease version
> Updating the isPrerelease version

- SafeguardDotNet.BrowserLogin/SafeguardDotNet.BrowserLogin.csproj
- SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
- SafeguardDotNet/SafeguardDotNet.csproj
- build-publish.yml
- build-test.yml
- pipeline-templates/build-steps.yml
- pipeline-templates/job-variables.yml
> TFS 490896 Code Signing Certificate
