SafeguardDotNet/A2A/ISafeguardA2AContext.cs
SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/Event/EventHandlerRegistry.cs
SafeguardDotNet/Event/ISafeguardEventListener.cs
SafeguardDotNet/Event/PersistentSafeguardA2AEventListener.cs
SafeguardDotNet/Event/PersistentSafeguardEventListener.cs
SafeguardDotNet/Event/PersistentSafeguardEventListenerBase.cs
SafeguardDotNet/Event/SafeguardEventListener.cs
SafeguardDotNet/Event/SafeguardEventListenerDisconnectedException.cs
SafeguardDotNet/ISafeguardConnection.cs
SafeguardDotNet/Safeguard.cs
SafeguardDotNet/SafeguardConnection.cs
SafeguardDotNet/SafeguardDotNet.csproj
Test/SafeguardDotNetA2aTool/Program.cs
Test/SafeguardDotNetEventTool/Program.cs
Test/SafeguardDotNetEventTool/ToolOptions.cs

Added the Safeguard.Event and Safeguard.A2A.Event resources for creating persistent event listeners.
These are robust SignalR event listeners that will reconnect even after a SignalR timeout.
They are a great building block for integration components.

Created persistent event listeners

---

SafeguardDotNet/CertificateUtilities.cs
SafeguardDotNet/Event/SafeguardEventListener.cs
Samples/ServiceNowTicketValidator/ConfigUtils.cs
Samples/ServiceNowTicketValidator/DTOs/AccessRequest.cs
Samples/ServiceNowTicketValidator/DTOs/AccessRequestApprovalPendingEvent.cs
Samples/ServiceNowTicketValidator/DTOs/Incident.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowCmdbCi.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowIncident.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowLink.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowResult.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowSysUser.cs
Samples/ServiceNowTicketValidator/DTOs/ServiceNowToken.cs
Samples/ServiceNowTicketValidator/Program.cs
Samples/ServiceNowTicketValidator/Properties/AssemblyInfo.cs
Samples/ServiceNowTicketValidator/README.md
Samples/ServiceNowTicketValidator/ServiceNowClient.cs
Samples/ServiceNowTicketValidator/ServiceNowTicketValidator.cs
Samples/ServiceNowTicketValidator/ServiceNowTicketValidator.csproj
Samples/ServiceNowTicketValidator/ServiceNowTicketValidator.sln
Samples/ServiceNowTicketValidator/ServiceNowTicketValidatorService.cs
Samples/ServiceNowTicketValidator/app.config
Samples/ServiceNowTicketValidator/packages.config
Test/SafeguardDotNetEventTool/Program.cs
Test/SafeguardDotNetEventTool/ToolOptions.cs
appveyor.yml

TopShelf service that can be run to perform legitimate ticket validation on ServiceNow tickets.
This is built using the SafeguardDotNet nuget package from nuget.org, not using the source code from the repo.
The current sample makes sure that the configuration item in the ticket matches the asset requested.
It also makes sure that the requester is the same as the assignee on the ticket.
This sample demonstrates:
- thumbprint-based client certificate authentication from a Windows host (most secure method)
- uses A2A for fetching credential to talk to ServiceNow
- uses client certificate and standard Safeguard API connection to act as automated approver
- uses persistent event listener to detect approval pending events
- parameters are loaded from app.config
- Serilog logging goes to a …

ServiceNow ticket system access request approver sample

---

SafeguardDotNet/A2A/ISafeguardA2AContext.cs
SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/Authentication/AccessTokenAuthenticator.cs
SafeguardDotNet/Authentication/AnonymousAuthenticator.cs
SafeguardDotNet/Authentication/AuthenticatorBase.cs
SafeguardDotNet/Authentication/CertificateAuthenticator.cs
SafeguardDotNet/Authentication/IAuthenticationMechanism.cs
SafeguardDotNet/Authentication/PasswordAuthenticator.cs
SafeguardDotNet/Event/EventHandlerRegistry.cs
SafeguardDotNet/Event/PersistentSafeguardA2AEventListener.cs
SafeguardDotNet/Event/PersistentSafeguardEventListener.cs
SafeguardDotNet/Event/PersistentSafeguardEventListenerBase.cs
SafeguardDotNet/ISafeguardConnection.cs
SafeguardDotNet/SafeguardConnection.cs
Test/SafeguardDotNetEventTool/Program.cs
Test/SafeguardDotNetTool/Program.cs

- Added convenience methods for creating persistent event listeners from SafeguardConnection and SafeguardA2AContext objects
- Added the ability to log out an existing SafeguardConnection, which invalidates and cleans up the Safeguard API access token
- Reduced the log levels in the library to more appropriate levels--some informational messages should have actually been debug

Listener and logout improvements

---

SafeguardDotNet/SafeguardDotNet.csproj
appveyor.yml

Updates:
- Added ability to log out a SafeguardConnection which invalidates the access token
- Added convenience method for requesting CSV response
- Added convenience methods for creating persistent event listeners
- Reduced the log level of certain messages
- API CHANGE:
- Renamed a method on ISafeguardA2AContext
- GetEventListener() is now GetA2AEventListener()
- GetPersistentA2AEventListener() should be preferred

Release 2.6

---

SafeguardDotNet/CertificateContext.cs

Unit testing this proved more convoluted than I thought, so I'm just committing the bug fix.

Null check the password in Clone

---

SafeguardDotNet/A2A/ISafeguardA2AContext.cs
SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/SafeguardDotNet.csproj
SafeguardDotNet/SafeguardDotNetTypes.cs
Test/SafeguardDotNetA2aTool/Program.cs
appveyor.yml

In Safeguard 2.8, A2A registrations are made optionally visible to the calling certificate user.  A new method on IA2AContext can get information on all of the accounts that it can request.

Add support for A2A credential retrieval API key discovery

---

SafeguardDotNet.sln
SafeguardDotNet/Authentication/AccessTokenAuthenticator.cs
SafeguardDotNet/Authentication/AnonymousAuthenticator.cs
SafeguardDotNet/Authentication/AuthenticatorBase.cs
SafeguardDotNet/Authentication/CertificateAuthenticator.cs
SafeguardDotNet/Authentication/IAuthenticationMechanism.cs
SafeguardDotNet/Authentication/PasswordAuthenticator.cs
SafeguardDotNet/SafeguardConnection.cs
Test/Invoke-SafeguardDotNetTests.ps1
Test/SafeguardDotNetTool/Program.cs
Test/SafeguardDotNetTool/ToolOptions.cs

Fix for #46 
I had stupidly broken the test script by hard-coding some IPs
Expanded the interface for authentication mechanisms and used that to check whether it was anonymous so that the connection class could determine whether or not to insert a token.

Fix anonymous authentication

---

SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/Authentication/AccessTokenAuthenticator.cs
SafeguardDotNet/Authentication/AnonymousAuthenticator.cs
SafeguardDotNet/Authentication/AuthenticatorBase.cs
SafeguardDotNet/Authentication/CertificateAuthenticator.cs
SafeguardDotNet/Authentication/IAuthenticationMechanism.cs
SafeguardDotNet/Authentication/PasswordAuthenticator.cs
SafeguardDotNet/CustomDelegateSslValidationHttpClient.cs
SafeguardDotNet/Event/SafeguardEventListener.cs
SafeguardDotNet/Safeguard.cs
SafeguardDotNet/SafeguardConnection.cs

Add a way for the caller to provide SafeguardDotNet with a certificate validation callback delegate.  This allows the caller to validate the SSL certificate without having to depend on the windows certificate validation.

Add custom SSL certificate validation

---

SafeguardDotNet/Authentication/AuthenticatorBase.cs
SafeguardDotNet/Authentication/CertificateAuthenticator.cs
SafeguardDotNet/Authentication/IAuthenticationMechanism.cs
SafeguardDotNet/Authentication/PasswordAuthenticator.cs
SafeguardDotNet/Safeguard.cs

- Updated certificate authenticator to allow for explicitly specified identity providers.
- Updated specified providers to allow for display name matches, just like safeguard-ps does. This allows the caller to specify the domain name for AD.

Certificate authentication updates

---

SafeguardDotNet/A2A/ISafeguardA2AContext.cs
SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/Event/PersistentSafeguardA2AEventListener.cs
SafeguardDotNet/Event/SafeguardEventListener.cs
SafeguardDotNet/SafeguardDotNetTypes.cs
Test/SafeguardDotNetA2aTool/Program.cs
Test/SafeguardDotNetA2aTool/ToolOptions.cs

Support for pulling SSH private keys via the A2A API.
I also found and fixed an issue with TLS validation for A2A event listeners.

Support for SSH private key in A2A

---

SafeguardDotNet/Authentication/AnonymousAuthenticator.cs
SafeguardDotNet/Authentication/PasswordAuthenticator.cs
SafeguardDotNet/ISafeguardConnection.cs
SafeguardDotNet/IStreamingRequest.cs
SafeguardDotNet/SafeguardConnection.cs
SafeguardDotNet/SafeguardDotNet.csproj
SafeguardDotNet/StreamingRequest.cs
SafeguardDotNet/UploadProgress.cs
Test/SafeguardDotNetA2aTool/ToolOptions.cs
Test/SafeguardDotNetTool/Program.cs
Test/SafeguardDotNetTool/ToolOptions.cs

Supports streaming uploads with progress. I wasn't able to use RestSharp for this (or I'm too dumb) so I've tried to implement it in a way that doesn't impact any of the existing code. There's a new streaming property on the ISafeguardConnection that gives access to the streaming functions which are implemented using the modern HttpClient and HttpRequestMessage.
Example code to upload a patch:
```csharp
// Connect as usual
ISafeguardConnection connection;
// Supports cancellation
CancellationTokenSource Cts;
// The stream to upload
using FileStream fs = File.OpenRead("patch.sgp");
// Supports progress
var progress = new Progress<UploadProgress>(p =>
{
Console.Write("\rUploading: {0,3}% ({1}/{2})                                             ", p.PercentComplete, p.BytesTransferred, …
```

Add support for streaming uploads

---

SafeguardDotNet/ISafeguardConnection.cs
SafeguardDotNet/SafeguardConnection.cs

There is no way currently to override the default timeout on a per-request basis. I need this for Patch/Install which can take longer than the default timeout to complete for slow VMs.

Add a per-request timeout parameter

---

SafeguardDotNet/StreamingRequest.cs

I didn't realize that SafeguardDotNetException attempts to parse the body here. If we get a non-200 result then read the body and set it so that error handling works as expected.

Fix streaming error handling

---

SafeguardDotNet/Sps/ISpsStreamingRequest.cs
SafeguardDotNet/Sps/SpsStreamingRequest.cs

Add DownloadStreamAsync for SPS that will be used by Safeguard-Supervisor
code to download an SPS support bundle after it has been created.
DownloadStreamAsync for SPS is based on, and nearly identical, to
DownloadStreamAsync for SPP.

TFS 317508 Implement SafeguardDotNet code to download file from SPS

---

SafeguardDotNet/A2A/SafeguardA2AContext.cs
SafeguardDotNet/Event/PersistentSafeguardA2AEventListener.cs

A2A context needs to return event listeners that are registered for API key events as well

Listen for API key changes

---

SafeguardDotNet.BrowserLogin/DefaultBrowserLogin.cs
SafeguardDotNet.BrowserLogin/SafeguardDotNet.BrowserLogin.csproj
SafeguardDotNet.BrowserLogin/TokenExtractor.cs
SafeguardDotNet.GuiLogin/LoginWindow.cs
SafeguardDotNet.GuiLogin/RstsWindow.cs
SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.csproj
SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.nuspec
SafeguardDotNet.GuiLogin/app.config
SafeguardDotNet.GuiLogin/packages.config
SafeguardDotNet.sln
SafeguardDotNet/Authentication/AuthenticatorBase.cs
SafeguardDotNet/Safeguard.cs
SafeguardDotNet/SafeguardDotNet.csproj
Samples/SampleA2aService/SampleA2aService.csproj
Samples/ServiceNowTicketValidator/ServiceNowClient.cs
Samples/ServiceNowTicketValidator/ServiceNowTicketValidator.csproj
Test/SafeguardDotNetA2aTool/SafeguardDotNetA2aTool.csproj
Test/SafeguardDotNetAccessRequestBrokerTool/SafeguardDotNetAccessRequestBrokerTool.csproj
Test/SafeguardDotNetBrowserLoginTester/SafeguardDotNetBrowserLoginTester.csproj
Test/SafeguardDotNetEventTool/SafeguardDotNetEventTool.csproj
Test/SafeguardDotNetExceptionTest/SafeguardDotNetExceptionTest.csproj
Test/SafeguardDotNetGuiTester/App.config
Test/SafeguardDotNetGuiTester/SafeguardDotNetGuiTester.csproj
Test/SafeguardDotNetGuiTester/packages.config
Test/SafeguardDotNetTool/SafeguardDotNetTool.csproj
Test/SafeguardSessionsDotNetTool/SafeguardSessionsDotNetTool.csproj

TFS 421334: Update SafeguardDotNet.BrowserLogin to use PKCE
TFS 421332: Update SafeguardDotNet.GuiLogin to use PKCE
Update GuiLogin to use the new WebView2 instead of older WebBrowser.
Move some common code into SafeguardDotNet instead of duplicating in GuiLogin and BrowserLogin.
Update RstsProviderScope to use Core/AuthenticationProviders endpoint.
Update from v3 to v4.
Clean up some pipeline build issues around conflicting older assembly versions i.e. CommandLine and Serilog.Sinks.Console and convert those to newer nuget packages.
Consolidate GuiLogin and GuiTester from 4.6.2 into 4.7.2 and samples SafeguardDotNet nuget 7.3.

TFS 403513: TD: Support PKCE in rSTS and stop using implicit flow from Safeguard clients

---

Test/Invoke-SafeguardDotNetTests.ps1

Remove the portion of the test script that elevates the privileges of the A2A certificate user before attempting to push a password using the A2A interface.  An exception was made in SPP to allow A2A certificate users the ability to push credentials using A2A. The test should not be elevating the permissions.

Don't elevate permissions for A2A credential push

---

SafeguardDotNet/Event/SafeguardEventListener.cs
SafeguardDotNet/SafeguardDotNet.csproj

Moving to SignalR 7.0.x and above, caused the connection to move to HTTP/2 rather than 1.1.  HTTP/2 does not support SSL renegotiation which is required by the HttpSys web host being used in SPP. Setting UseDefaultCredentials = true, forces the connection back to HTTP/1.1 which allows SSL renegotiation.
Addition Information:
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0#renegotiation
Part of the SignalR 7.x release was to "upgrade" to using HTTP/2 instead of HTTP/1.1. https://github.com/dotnet/aspnetcore/commit/9c8ad7359a07748135d2e144ace41ce956b3365a#diff-e5214ac6828c579117d0cff7efecfbfa79d03d7f96fc2b09f174dd28f67f349dL465
In the SignalR 7.0.7 version, some logic was added that forces the HTTP version back down to 1.1 …

Force SignalR in SafeguardDonet to use HTTP/1.1 protocol which allows SSL renegotiation

---

SafeguardDotNet/Sps/SafeguardSessionsConnection.cs

With the upgrade of RestSharp, it no longer retains cookies on the client level. This fix just instructs the client to revert to the previous behavior.

Keep the session cookie at the client level

---

SafeguardDotNet/SafeguardConnection.cs
SafeguardDotNet/SafeguardDotNet.csproj

Update the RestSharp NuGet package reference to version 112, which fixes a CRLF header vulnerability: https://github.com/advisories/GHSA-4rr6-2v9v-wcpc
https://github.com/restsharp/RestSharp/releases/tag/112.0.0

Update RestSharp NuGet Package

---

SafeguardDotNet.BrowserLogin/TokenExtractor.cs

There was a mix up in variables.
For Issue #180.

Username not being passed in BrowserLogin.DefaultBrowserLogin.Connect()

---

SafeguardDotNet/A2A/SafeguardA2AContext.cs

Fixes issue #189. When calling the `PUT` method of the A2A `Credentials/Password` API, the code was taking the password value and blindly wrapping it in double quotes to try and make a JSON string object. But that would fail if the password value had a double quote character itself or other things.
So now, we properly serialize the password string value to a JSON string, with proper escaping.

Set A2A Password
